name: CI-CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Check application files
        run: |
          echo "Checking application files..."

          test -f index.html
          test -f appspec.yml
          test -f scripts/stop_server.sh
          test -f scripts/install_dependencies.sh
          test -f scripts/start_server.sh

          echo "All required files found!"

      - name: Validate AppSpec
        run: |
          grep -q "version: 0.0" appspec.yml
          grep -q "os: linux" appspec.yml
          echo "AppSpec validation passed!"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::485726107958:role/GitHubActionsCodeDeployRole
          aws-region: ap-south-2

      - name: Test AWS connection
        run: |
          aws sts get-caller-identity

      - name: Create development package
        run: |
          zip -r development.zip index.html appspec.yml scripts/

      - name: Upload development package to S3
        run: |
          aws s3 cp development.zip \
            s3://task-4-staticwebsite-container1/development/${{ github.sha }}.zip

          echo "development package uploaded successfully!"
